application: repreapproval
version: 2
runtime: python
api_version: 1
threadsafe: yes

handlers:

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /demo
  static_dir: static/pages/demo

- url: /docs
  static_dir: static/pages/docs

- url: .*
  script: main.py
