application: repreapproval
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /data
  static_dir: static/data

- url: /js
  static_dir: static/js

- url: /libs
  static_dir: static/libs

- url: /templates
  static_dir: static/templates

- url: /
  static_files: static/index.html
  upload: static/(.*)

- url: .*
  script: repreapproval.app

libraries:
- name: jinja2
  version: latest